import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const studySessions = pgTable(
  "study_sessions",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    sourceType: text("source_type").notNull(), // 'pdf' | 'image' | 'docx' | 'mixed' | 'text'
    sourceText: text("source_text"),
    /** 1-2 sentence description of the deck, generated by the AI. */
    summary: text("summary"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("study_sessions_created_at_idx").on(table.createdAt)]
);

export const flashcards = pgTable(
  "flashcards",
  {
    id: serial("id").primaryKey(),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    hint: text("hint"),
    difficulty: text("difficulty").notNull().default("medium"), // 'easy' | 'medium' | 'hard'
    orderIndex: integer("order_index").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("flashcards_session_id_idx").on(table.sessionId)]
);

export const cardProgress = pgTable(
  "card_progress",
  {
    id: serial("id").primaryKey(),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    isKnown: boolean("is_known").notNull().default(false),
    attempts: integer("attempts").notNull().default(0),
    lastReviewedAt: timestamp("last_reviewed_at").defaultNow(),
  },
  (table) => [
    // One progress row per (card, session) pair — makes upserts atomic and
    // the session-list "known" counts reliable.
    uniqueIndex("card_progress_card_session_key").on(table.cardId, table.sessionId),
    index("card_progress_session_id_idx").on(table.sessionId),
    index("card_progress_card_id_idx").on(table.cardId),
  ]
);

export type StudySession = typeof studySessions.$inferSelect;
export type Flashcard = typeof flashcards.$inferSelect;
export type CardProgress = typeof cardProgress.$inferSelect;
