import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  // Provider account id (Google's `sub`) — stable and deterministic.
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  image: text("image"),
  provider: text("provider").notNull().default("google"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const studySessions = pgTable(
  "study_sessions",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    sourceType: text("source_type").notNull(), // 'pdf' | 'image' | 'docx' | 'mixed' | 'text'
    sourceText: text("source_text"),
    /** 1-2 sentence description of the deck, generated by the AI. */
    summary: text("summary"),
    /**
     * Owner of the deck. Nullable for now so the migration is safe on
     * databases created before accounts existed; flip to notNull() once
     * legacy decks are adopted or purged.
     */
    userId: text("user_id").references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_sessions_created_at_idx").on(table.createdAt),
    index("study_sessions_user_id_idx").on(table.userId),
  ]
);

export const flashcards = pgTable(
  "flashcards",
  {
    id: serial("id").primaryKey(),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    hint: text("hint"),
    difficulty: text("difficulty").notNull().default("medium"), // 'easy' | 'medium' | 'hard'
    orderIndex: integer("order_index").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("flashcards_session_id_idx").on(table.sessionId)]
);

export const cardProgress = pgTable(
  "card_progress",
  {
    id: serial("id").primaryKey(),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    isKnown: boolean("is_known").notNull().default(false),
    attempts: integer("attempts").notNull().default(0),
    lastReviewedAt: timestamp("last_reviewed_at").defaultNow(),
  },
  (table) => [
    // One progress row per (card, session) pair — makes upserts atomic and
    // the session-list "known" counts reliable.
    uniqueIndex("card_progress_card_session_key").on(table.cardId, table.sessionId),
    index("card_progress_session_id_idx").on(table.sessionId),
    index("card_progress_card_id_idx").on(table.cardId),
  ]
);

export const studyResults = pgTable(
  "study_results",
  {
    id: serial("id").primaryKey(),
    /** Owner of the result — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    /** Deck (study_sessions row) the answered card belongs to. */
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    /** The flashcard that was answered. */
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    /** Right/wrong signal — the foundation P4's spaced repetition consumes. */
    correct: boolean("correct").notNull(),
    /** Which mode produced the outcome: 'study' (self-check) or 'exam' (MCQ). */
    mode: text("mode").notNull().default("study"),
    answeredAt: timestamp("answered_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_results_user_id_idx").on(table.userId),
    index("study_results_session_id_idx").on(table.sessionId),
    index("study_results_card_id_idx").on(table.cardId),
    // Streaks + overall stats are per-user time-range queries.
    index("study_results_user_answered_idx").on(table.userId, table.answeredAt),
  ]
);

export type User = typeof users.$inferSelect;
export type StudySession = typeof studySessions.$inferSelect;
export type Flashcard = typeof flashcards.$inferSelect;
export type CardProgress = typeof cardProgress.$inferSelect;
export type StudyResult = typeof studyResults.$inferSelect;
